site_name: 蒟蒻二叉树的博客
site_url: https://comlete-binary-tree-blog.github.io/
use_directory_urls: true
repo_url: https://github.com/comlete-binary-tree-blog/comlete-binary-tree-blog.github.io # 仓库地址
repo_name: comlete-binary-tree-blog.github.io # 仓库名称
edit_uri: edit/main/docs # 编辑地址
edit_uri_template: null # 编辑地址模板
site_description: 蒟蒻二叉树的博客 # 站点描述
site_author: comlete-binary-tree # 站点作者
copyright: <a href="#__consent">修改 Cookie 设置</a><br/>Copyright &copy; 2025 Complete-binary-tree # 版权信息和 Cookie 设置
remote_branch: page # GitHub Pages 远程分支名称
remote_name: origin # 远程名称
docs_dir: docs # 文档目录
site_dir: site # 网站目录
#site_url: http://10.110.169.28:8000
dev_addr: localhost:8080
nav:
  - 主页: 
    - 概览: index.md
    - 关于: about.md
    - Todo-list: Todo.md
  - OI:
    - OI 简介: OI/index.md
    - 常用网站: OI/websites.md
    - C++ 语法:
      - C++ 简介: OI/C++/index.md
      - OI/C++/STL.md
    - Python 语法: []
    - 算法:
      - 算法简介: OI/Algorithm/index.md
      - 数据结构:
        - 数据结构简介: OI/Algorithm/DataStructure/index.md
        - log 数据结构:
          - log 数据结构简介: OI/Algorithm/DataStructure/LogStructure/index.md
          - 线段树: OI/Algorithm/DataStructure/LogStructure/SegmentTree.md
  - 教程: 
    - 教程简介: 教程/index.md
    - MkDocs:
      - 教程/如何使用 MkDocs 搭建你的文章/index.md
  - 日记:
    - 日记简介: Journal/index.md


theme:
    name: material
    language: zh
    features:
        - navigation.instant
        - search-suggest
        - navigation.instant.progress
        - navigation.tabs
        #- navigation.footer
        #- header.autohide
        - content.code.copy
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/weather-night
            name: Switch to dark mode

          primary: white
          accent: red

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/weather-sunny
            name: Switch to system preference

          primary: black
          accent: cyan
    favicon: "favicon.ico"
    icon:
      logo: material/school

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/complete-binary-tree-blog
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3493146728073249

#extra_javascript:
  #- javascripts/mathjax.js
  #- https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins: 
    - tags
    - search

hooks:
  - hooks/on_env.py

markdown_extensions:
  #- md4mathjax
  - document-offsets-injection
  - admonition
  - def_list
  - attr_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
      
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true