site_name: 蒟蒻二叉树的博客
site_url: https://comlete-binary-tree-blog.github.io
nav:
    - 主页: index.md
    - 关于: about.md
    - OI:
        - OI 简介: OI/index.md
        - 常用网站: OI/websites.md
        - C++ 语法:
            - C++ 简介: OI/C++/index.md
            - OI/C++/STL.md
    - 教程: 
        - 教程简介: 教程/index.md
        - MkDocs:
            - 教程/如何使用 MkDocs 搭建你的文章/index.md
    - 日记:
        - 日记简介: Journal/index.md


theme:
    name: material
    features:
        - navigation.instant
        - search-suggest
        - navigation.instant.progress
        - navigation.tabs
        - navigation.footer
    #- header.autohide
    palette:
        # Palette toggle for automatic mode
        - media: "(prefers-color-scheme)"
          toggle:
            icon: material/brightness-auto
            name: Switch to light mode

        # Palette toggle for light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default 
          toggle:
            icon: material/weather-night
            name: Switch to dark mode

          primary: white
          accent: red

        # Palette toggle for dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          toggle:
            icon: material/weather-sunny
            name: Switch to system preference

          primary: black
          accent: red

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/complete-binary-tree-blog
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/3493146728073249

plugins: 
    - tags
    - search

hooks:
  - hooks/on_env.py

markdown_extensions:
  - md4mathjax
  - document-offsets-injection
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: ""
      slugify: !!python/name:pymdownx.slugs.uslugify
  #- pymdownx.arithmatex:
  #    generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets:
      check_paths: true
      
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true